/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/cyber_skull_low.glb -o src/components/CyberSkull.jsx 
Author: Idmental (https://sketchfab.com/idmental.id)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyber-skull-lowpoly-free-asset-bc6fdb51f3f4430c8efc71d906900d36
Title: CYBER SKULL [lowpoly] [ free asset ]
*/

import { MeshStandardMaterial } from "three";
import { useGLTF } from "@react-three/drei";

export function CyberSkull(props) {
  const { nodes, materials } = useGLTF("/models/cyber_skull_low.glb");

  const playerColorMaterial = new MeshStandardMaterial({
    color: "white",
    toneMapped: true,
  });

  playerColorMaterial.color.multiplyScalar(3);

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.skull_NFT_lowpoly_default11_0.geometry}
          material={playerColorMaterial}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/cyber_skull_low.glb");
