/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/cyber.glb 
*/

import { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Cyber(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/cyber.glb");
  const { actions, mixer } = useAnimations(animations, group);

  // useEffect(() => {
  //   actions[`Armature|mixamo.com|Layer0
  //   `].play();
  //   mixer.timeScale = 1;
  // }, [actions, mixer]);

  console.log(actions);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="Ch44">
            <skinnedMesh
              name="Mesh"
              geometry={nodes.Mesh.geometry}
              material={nodes.Mesh.material}
              skeleton={nodes.Mesh.skeleton}
            />
            <skinnedMesh
              name="Mesh_1"
              geometry={nodes.Mesh_1.geometry}
              material={nodes.Mesh_1.material}
              skeleton={nodes.Mesh_1.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/cyber.glb");
