/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/gayeti_hellhound.glb -o src/components/Hellhound.jsx 
Author: Gayeti (https://sketchfab.com/gayeti)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gayeti-hellhound-f7906538199e4cc9bf65aaa7f30eb278
Title: Gayeti HellHound
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Hellhound(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/gayeti_hellhound.glb"
  );
  const { actions, mixer } = useAnimations(animations, group);

  useEffect(() => {
    actions["drakee"].play();
    mixer.timeScale = 1;
  }, [actions, mixer]);

  console.log(actions);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="40181e0dc8514308905ee4ba292d9d4bfbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group
                    name="Object_6"
                    position={[0, 0.619, -0.186]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Drake"
                    position={[0, 0.619, -0.186]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Drake}
                    skeleton={nodes.Object_7.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/gayeti_hellhound.glb");
